location = /__l5e/assets-v1/922a05f2-13ca-47e7-8685-8cc75eb681de/seovale-coin-dark.jpg {
    alias /opt/seovale-static/seovale-coin-dark.jpg;
    default_type image/jpeg;
    expires 365d;
    add_header X-Content-Type-Options nosniff always;
}

location = /__l5e/assets-v1/4d0a28ae-cae7-4867-adaf-010ad9bc4af0/seovale-coin-light.jpg {
    alias /opt/seovale-static/seovale-coin-light.jpg;
    default_type image/jpeg;
    expires 365d;
    add_header X-Content-Type-Options nosniff always;
}
