/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedLicensingRouteImport } from './routes/_authenticated/licensing'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedRemovalsRouteImport } from './routes/_authenticated/removals'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedResponsesRouteImport } from './routes/_authenticated/responses'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedScansRouteImport } from './routes/_authenticated/scans'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as ApiPublicRemovalScanRouteImport } from './routes/api/public/removal-scan'
import { Route as ApiPublicGoogleBusinessCallbackRouteImport } from './routes/api/public/google-business/callback'
import { Route as ApiPublicIntegrationsCallbackRouteImport } from './routes/api/public/integrations/callback'
import { Route as ApiPublicIntegrationsJobsRunRouteImport } from './routes/api/public/integrations/jobs-run'
import { Route as ApiPublicIntegrationsWebhookRouteImport } from './routes/api/public/integrations/webhook'
import { Route as ApiPublicLicenseActivateRouteImport } from './routes/api/public/license/activate'
import { Route as ApiPublicLicenseDownloadRouteImport } from './routes/api/public/license/download'
import { Route as ApiPublicLicenseUpdateCheckRouteImport } from './routes/api/public/license/update-check'
import { Route as ApiPublicLicenseValidateRouteImport } from './routes/api/public/license/validate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLicensingRoute = AuthenticatedLicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemovalsRoute = AuthenticatedRemovalsRouteImport.update({
  id: '/removals',
  path: '/removals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResponsesRoute = AuthenticatedResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScansRoute = AuthenticatedScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRemovalScanRoute = ApiPublicRemovalScanRouteImport.update({
  id: '/api/public/removal-scan',
  path: '/api/public/removal-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleBusinessCallbackRoute =
  ApiPublicGoogleBusinessCallbackRouteImport.update({
    id: '/api/public/google-business/callback',
    path: '/api/public/google-business/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsCallbackRoute =
  ApiPublicIntegrationsCallbackRouteImport.update({
    id: '/api/public/integrations/callback',
    path: '/api/public/integrations/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsJobsRunRoute =
  ApiPublicIntegrationsJobsRunRouteImport.update({
    id: '/api/public/integrations/jobs-run',
    path: '/api/public/integrations/jobs-run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsWebhookRoute =
  ApiPublicIntegrationsWebhookRouteImport.update({
    id: '/api/public/integrations/webhook',
    path: '/api/public/integrations/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseActivateRoute =
  ApiPublicLicenseActivateRouteImport.update({
    id: '/api/public/license/activate',
    path: '/api/public/license/activate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseDownloadRoute =
  ApiPublicLicenseDownloadRouteImport.update({
    id: '/api/public/license/download',
    path: '/api/public/license/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseUpdateCheckRoute =
  ApiPublicLicenseUpdateCheckRouteImport.update({
    id: '/api/public/license/update-check',
    path: '/api/public/license/update-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseValidateRoute =
  ApiPublicLicenseValidateRouteImport.update({
    id: '/api/public/license/validate',
    path: '/api/public/license/validate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/licensing': typeof AuthenticatedLicensingRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/removals': typeof AuthenticatedRemovalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/responses': typeof AuthenticatedResponsesRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/scans': typeof AuthenticatedScansRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/system': typeof AuthenticatedSystemRoute
  '/api/public/removal-scan': typeof ApiPublicRemovalScanRoute
  '/api/public/google-business/callback': typeof ApiPublicGoogleBusinessCallbackRoute
  '/api/public/integrations/callback': typeof ApiPublicIntegrationsCallbackRoute
  '/api/public/integrations/jobs-run': typeof ApiPublicIntegrationsJobsRunRoute
  '/api/public/integrations/webhook': typeof ApiPublicIntegrationsWebhookRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/download': typeof ApiPublicLicenseDownloadRoute
  '/api/public/license/update-check': typeof ApiPublicLicenseUpdateCheckRoute
  '/api/public/license/validate': typeof ApiPublicLicenseValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/licensing': typeof AuthenticatedLicensingRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/removals': typeof AuthenticatedRemovalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/responses': typeof AuthenticatedResponsesRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/scans': typeof AuthenticatedScansRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/system': typeof AuthenticatedSystemRoute
  '/api/public/removal-scan': typeof ApiPublicRemovalScanRoute
  '/api/public/google-business/callback': typeof ApiPublicGoogleBusinessCallbackRoute
  '/api/public/integrations/callback': typeof ApiPublicIntegrationsCallbackRoute
  '/api/public/integrations/jobs-run': typeof ApiPublicIntegrationsJobsRunRoute
  '/api/public/integrations/webhook': typeof ApiPublicIntegrationsWebhookRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/download': typeof ApiPublicLicenseDownloadRoute
  '/api/public/license/update-check': typeof ApiPublicLicenseUpdateCheckRoute
  '/api/public/license/validate': typeof ApiPublicLicenseValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/licensing': typeof AuthenticatedLicensingRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/removals': typeof AuthenticatedRemovalsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/responses': typeof AuthenticatedResponsesRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/scans': typeof AuthenticatedScansRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/system': typeof AuthenticatedSystemRoute
  '/api/public/removal-scan': typeof ApiPublicRemovalScanRoute
  '/api/public/google-business/callback': typeof ApiPublicGoogleBusinessCallbackRoute
  '/api/public/integrations/callback': typeof ApiPublicIntegrationsCallbackRoute
  '/api/public/integrations/jobs-run': typeof ApiPublicIntegrationsJobsRunRoute
  '/api/public/integrations/webhook': typeof ApiPublicIntegrationsWebhookRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/download': typeof ApiPublicLicenseDownloadRoute
  '/api/public/license/update-check': typeof ApiPublicLicenseUpdateCheckRoute
  '/api/public/license/validate': typeof ApiPublicLicenseValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alerts'
    | '/analytics'
    | '/competitors'
    | '/dashboard'
    | '/feedback'
    | '/integrations'
    | '/licensing'
    | '/locations'
    | '/removals'
    | '/reports'
    | '/responses'
    | '/reviews'
    | '/scans'
    | '/settings'
    | '/support'
    | '/system'
    | '/api/public/removal-scan'
    | '/api/public/google-business/callback'
    | '/api/public/integrations/callback'
    | '/api/public/integrations/jobs-run'
    | '/api/public/integrations/webhook'
    | '/api/public/license/activate'
    | '/api/public/license/download'
    | '/api/public/license/update-check'
    | '/api/public/license/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alerts'
    | '/analytics'
    | '/competitors'
    | '/dashboard'
    | '/feedback'
    | '/integrations'
    | '/licensing'
    | '/locations'
    | '/removals'
    | '/reports'
    | '/responses'
    | '/reviews'
    | '/scans'
    | '/settings'
    | '/support'
    | '/system'
    | '/api/public/removal-scan'
    | '/api/public/google-business/callback'
    | '/api/public/integrations/callback'
    | '/api/public/integrations/jobs-run'
    | '/api/public/integrations/webhook'
    | '/api/public/license/activate'
    | '/api/public/license/download'
    | '/api/public/license/update-check'
    | '/api/public/license/validate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/alerts'
    | '/_authenticated/analytics'
    | '/_authenticated/competitors'
    | '/_authenticated/dashboard'
    | '/_authenticated/feedback'
    | '/_authenticated/integrations'
    | '/_authenticated/licensing'
    | '/_authenticated/locations'
    | '/_authenticated/removals'
    | '/_authenticated/reports'
    | '/_authenticated/responses'
    | '/_authenticated/reviews'
    | '/_authenticated/scans'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/system'
    | '/api/public/removal-scan'
    | '/api/public/google-business/callback'
    | '/api/public/integrations/callback'
    | '/api/public/integrations/jobs-run'
    | '/api/public/integrations/webhook'
    | '/api/public/license/activate'
    | '/api/public/license/download'
    | '/api/public/license/update-check'
    | '/api/public/license/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicRemovalScanRoute: typeof ApiPublicRemovalScanRoute
  ApiPublicGoogleBusinessCallbackRoute: typeof ApiPublicGoogleBusinessCallbackRoute
  ApiPublicIntegrationsCallbackRoute: typeof ApiPublicIntegrationsCallbackRoute
  ApiPublicIntegrationsJobsRunRoute: typeof ApiPublicIntegrationsJobsRunRoute
  ApiPublicIntegrationsWebhookRoute: typeof ApiPublicIntegrationsWebhookRoute
  ApiPublicLicenseActivateRoute: typeof ApiPublicLicenseActivateRoute
  ApiPublicLicenseDownloadRoute: typeof ApiPublicLicenseDownloadRoute
  ApiPublicLicenseUpdateCheckRoute: typeof ApiPublicLicenseUpdateCheckRoute
  ApiPublicLicenseValidateRoute: typeof ApiPublicLicenseValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licensing': {
      id: '/_authenticated/licensing'
      path: '/licensing'
      fullPath: '/licensing'
      preLoaderRoute: typeof AuthenticatedLicensingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/removals': {
      id: '/_authenticated/removals'
      path: '/removals'
      fullPath: '/removals'
      preLoaderRoute: typeof AuthenticatedRemovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/responses': {
      id: '/_authenticated/responses'
      path: '/responses'
      fullPath: '/responses'
      preLoaderRoute: typeof AuthenticatedResponsesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scans': {
      id: '/_authenticated/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof AuthenticatedScansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/removal-scan': {
      id: '/api/public/removal-scan'
      path: '/api/public/removal-scan'
      fullPath: '/api/public/removal-scan'
      preLoaderRoute: typeof ApiPublicRemovalScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-business/callback': {
      id: '/api/public/google-business/callback'
      path: '/api/public/google-business/callback'
      fullPath: '/api/public/google-business/callback'
      preLoaderRoute: typeof ApiPublicGoogleBusinessCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/callback': {
      id: '/api/public/integrations/callback'
      path: '/api/public/integrations/callback'
      fullPath: '/api/public/integrations/callback'
      preLoaderRoute: typeof ApiPublicIntegrationsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/jobs-run': {
      id: '/api/public/integrations/jobs-run'
      path: '/api/public/integrations/jobs-run'
      fullPath: '/api/public/integrations/jobs-run'
      preLoaderRoute: typeof ApiPublicIntegrationsJobsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/webhook': {
      id: '/api/public/integrations/webhook'
      path: '/api/public/integrations/webhook'
      fullPath: '/api/public/integrations/webhook'
      preLoaderRoute: typeof ApiPublicIntegrationsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/activate': {
      id: '/api/public/license/activate'
      path: '/api/public/license/activate'
      fullPath: '/api/public/license/activate'
      preLoaderRoute: typeof ApiPublicLicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/download': {
      id: '/api/public/license/download'
      path: '/api/public/license/download'
      fullPath: '/api/public/license/download'
      preLoaderRoute: typeof ApiPublicLicenseDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/update-check': {
      id: '/api/public/license/update-check'
      path: '/api/public/license/update-check'
      fullPath: '/api/public/license/update-check'
      preLoaderRoute: typeof ApiPublicLicenseUpdateCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/validate': {
      id: '/api/public/license/validate'
      path: '/api/public/license/validate'
      fullPath: '/api/public/license/validate'
      preLoaderRoute: typeof ApiPublicLicenseValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLicensingRoute: typeof AuthenticatedLicensingRoute
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedRemovalsRoute: typeof AuthenticatedRemovalsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedResponsesRoute: typeof AuthenticatedResponsesRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedScansRoute: typeof AuthenticatedScansRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLicensingRoute: AuthenticatedLicensingRoute,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedRemovalsRoute: AuthenticatedRemovalsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedResponsesRoute: AuthenticatedResponsesRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedScansRoute: AuthenticatedScansRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicRemovalScanRoute: ApiPublicRemovalScanRoute,
  ApiPublicGoogleBusinessCallbackRoute: ApiPublicGoogleBusinessCallbackRoute,
  ApiPublicIntegrationsCallbackRoute: ApiPublicIntegrationsCallbackRoute,
  ApiPublicIntegrationsJobsRunRoute: ApiPublicIntegrationsJobsRunRoute,
  ApiPublicIntegrationsWebhookRoute: ApiPublicIntegrationsWebhookRoute,
  ApiPublicLicenseActivateRoute: ApiPublicLicenseActivateRoute,
  ApiPublicLicenseDownloadRoute: ApiPublicLicenseDownloadRoute,
  ApiPublicLicenseUpdateCheckRoute: ApiPublicLicenseUpdateCheckRoute,
  ApiPublicLicenseValidateRoute: ApiPublicLicenseValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
